---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: lazyuser
  become: true
  tasks:

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Pull Docker Image
      docker_image:
        name: "dhruvikpatel48/calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result    
    
    - name: Running container
      shell: docker run -it -d --name calculator dhruvikpatel48/calculator